export type AtomParams = {
    electrons: number[]
    mass: number
    label: string
    number: number
    name: string
    neutronCount: number
}

export const listElements: AtomParams[] = [
    {
        electrons: [1],
        mass: 1.01,
        label: "Водород",
        number: 1,
        name: "H",
        neutronCount: 0,
    },
    {
        electrons: [2],
        mass: 4.00,
        label: "Гелий",
        number: 2,
        name: "He",
        neutronCount: 2,
    },
    {
        electrons: [2, 1],
        mass: 6.94,
        label: "Литий",
        number: 3,
        name: "Li",
        neutronCount: 4,
    },
    {
        electrons: [2, 2],
        mass: 9.01,
        label: "Бериллий",
        number: 4,
        name: "Be",
        neutronCount: 5,
    },
    {
        electrons: [2, 3],
        mass: 10.81,
        label: "Бор",
        number: 5,
        name: "B",
        neutronCount: 6,
    },
    {
        electrons: [2, 4],
        mass: 12.01,
        label: "Углерод",
        number: 6,
        name: "C",
        neutronCount: 6,
    },
    {
        electrons: [2, 5],
        mass: 14.01,
        label: "Азот",
        number: 7,
        name: "N",
        neutronCount: 7,
    },
    {
        electrons: [2, 6],
        mass: 16.00,
        label: "Кислород",
        number: 8,
        name: "O",
        neutronCount: 8,
    },
    {
        electrons: [2, 7],
        mass: 19.00,
        label: "Фтор",
        number: 9,
        name: "F",
        neutronCount: 10,
    },
    {
        electrons: [2, 8],
        mass: 20.18,
        label: "Неон",
        number: 10,
        name: "Ne",
        neutronCount: 10,
    },
    {
        electrons: [2, 8, 1],
        mass: 22.99,
        label: "Натрий",
        number: 11,
        name: "Na",
        neutronCount: 12,
    },
    {
        electrons: [2, 8, 2],
        mass: 24.31,
        label: "Магний",
        number: 12,
        name: "Mg",
        neutronCount: 12,
    },
    {
        electrons: [2, 8, 3],
        mass: 26.98,
        label: "Алюминий",
        number: 13,
        name: "Al",
        neutronCount: 14,
    },
    {
        electrons: [2, 8, 4],
        mass: 28.09,
        label: "Кремний",
        number: 14,
        name: "Si",
        neutronCount: 14,
    },
    {
        electrons: [2, 8, 5],
        mass: 30.97,
        label: "Фосфор",
        number: 15,
        name: "P",
        neutronCount: 16,
    },
    {
        electrons: [2, 8, 6],
        mass: 32.07,
        label: "Сера",
        number: 16,
        name: "S",
        neutronCount: 16,
    },
    {
        electrons: [2, 8, 7],
        mass: 35.45,
        label: "Хлор",
        number: 17,
        name: "Cl",
        neutronCount: 18,
    },
    {
        electrons: [2, 8, 8],
        mass: 39.95,
        label: "Аргон",
        number: 18,
        name: "Ar",
        neutronCount: 22,
    },
    {
        electrons: [2, 8, 8, 1],
        mass: 39.09,
        label: "Калий",
        number: 19,
        name: "K",
        neutronCount: 20,
    },
    {
        electrons: [2, 8, 8, 2],
        mass: 40.08,
        label: "Кальций",
        number: 20,
        name: "Ca",
        neutronCount: 20,
    },
    {
        electrons: [2, 8, 9, 2],
        mass: 44.96,
        label: "Скандий",
        number: 21,
        name: "Sc",
        neutronCount: 24,
    },
    {
        electrons: [2, 8, 10, 2],
        mass: 47.90,
        label: "Титан",
        number: 22,
        name: "Ti",
        neutronCount: 26,
    },
    {
        electrons: [2, 8, 11, 2],
        mass: 50.94,
        label: "Ванадий",
        number: 23,
        name: "V",
        neutronCount: 28,
    },
    {
        electrons: [2, 8, 13, 1],
        mass: 52.00,
        label: "Хром",
        number: 24,
        name: "Cr",
        neutronCount: 28,
    },
    {
        electrons: [2, 8, 13, 2],
        mass: 54.94,
        label: "Марганец",
        number: 25,
        name: "Mn",
        neutronCount: 30,
    },
    {
        electrons: [2, 8, 14, 2],
        mass: 55.85,
        label: "Железо",
        number: 26,
        name: "Fe",
        neutronCount: 30,
    },
    {
        electrons: [2, 8, 15, 2],
        mass: 58.93,
        label: "Кобальт",
        number: 27,
        name: "Co",
        neutronCount: 32,
    },
    {
        electrons: [2, 8, 16, 2],
        mass: 58.70,
        label: "Никель",
        number: 28,
        name: "Ni",
        neutronCount: 31,
    },
    {
        electrons: [2, 8, 18, 1],
        mass: 63.55,
        label: "Медь",
        number: 29,
        name: "Cu",
        neutronCount: 35,
    },
    {
        electrons: [2, 8, 18, 2],
        mass: 65.39,
        label: "Цинк",
        number: 30,
        name: "Zn",
        neutronCount: 35,
    },
    {
        electrons: [2, 8, 18, 3],
        mass: 69.72,
        label: "Галий",
        number: 31,
        name: "Ga",
        neutronCount: 39,
    },
    {
        electrons: [2, 8, 18, 4],
        mass: 72.59,
        label: "Германий",
        number: 32,
        name: "Ge",
        neutronCount: 41,
    },
    {
        electrons: [2, 8, 18, 5],
        mass: 75.00,
        label: "Мышьяк",
        number: 33,
        name: "As",
        neutronCount: 42,
    },
    {
        electrons: [2, 8, 18, 6],
        mass: 78.96,
        label: "Селен",
        number: 34,
        name: "Se",
        neutronCount: 45,
    },
    {
        electrons: [2, 8, 18, 7],
        mass: 79.90,
        label: "Бром",
        number: 35,
        name: "Br",
        neutronCount: 45,
    },
    {
        electrons: [2, 8, 18, 8],
        mass: 83.80,
        label: "Криптон",
        number: 36,
        name: "Kr",
        neutronCount: 48,
    },
    {
        electrons: [2, 8, 18, 8, 1],
        mass: 85.47,
        label: "Рубидий",
        number: 37,
        name: "Rb",
        neutronCount: 48,
    },
    {
        electrons: [2, 8, 18, 8, 2],
        mass: 87.62,
        label: "Стронций",
        number: 38,
        name: "Sr",
        neutronCount: 50,
    },
    {
        electrons: [2, 8, 18, 9, 2],
        mass: 88.91,
        label: "Иттрий",
        number: 39,
        name: "Y",
        neutronCount: 50,
    },
    {
        electrons: [2, 8, 18, 10, 2],
        mass: 91.22,
        label: "Цирконий",
        number: 40,
        name: "Zr",
        neutronCount: 51,
    },
    {
        electrons: [2, 8, 18, 12, 1],
        mass: 92.91,
        label: "Ниобий",
        number: 41,
        name: "Nb",
        neutronCount: 52,
    },
    {
        electrons: [2, 8, 18, 13, 1],
        mass: 95.94,
        label: "Молибден",
        number: 42,
        name: "Mo",
        neutronCount: 54,
    },
    {
        electrons: [2, 8, 18, 13, 2],
        mass: 97.91,
        label: "Технеций",
        number: 43,
        name: "Tc",
        neutronCount: 55,
    },
    {
        electrons: [2, 8, 18, 15, 1],
        mass: 101.07,
        label: "Рутений",
        number: 44,
        name: "Ru",
        neutronCount: 57,
    },
    {
        electrons: [2, 8, 18, 16, 1],
        mass: 102.91,
        label: "Родий",
        number: 45,
        name: "Rh",
        neutronCount: 58,
    },
    {
        electrons: [2, 8, 18, 18],
        mass: 106.4,
        label: "Палладий",
        number: 46,
        name: "Pd",
        neutronCount: 60,
    },
    {
        electrons: [2, 8, 18, 18, 1],
        mass: 107.87,
        label: "Серебро",
        number: 47,
        name: "Ag",
        neutronCount: 61,
    },
    {
        electrons: [2, 8, 18, 18, 2],
        mass: 112.41,
        label: "Кадмий",
        number: 48,
        name: "Cd",
        neutronCount: 64,
    },
    {
        electrons: [2, 8, 18, 18, 3],
        mass: 114.82,
        label: "Индий",
        number: 49,
        name: "In",
        neutronCount: 66,
    },
    {
        electrons: [2, 8, 18, 18, 4],
        mass: 118.71,
        label: "Олово",
        number: 50,
        name: "Sn",
        neutronCount: 69,
    },
    {
        electrons: [2, 8, 18, 18, 5],
        mass: 121.75,
        label: "Сурьма",
        number: 51,
        name: "Sb",
        neutronCount: 71,
    },
    {
        electrons: [2, 8, 18, 18, 6],
        mass: 127.6,
        label: "Теллур",
        number: 52,
        name: "Te",
        neutronCount: 76,
    },
    {
        electrons: [2, 8, 18, 18, 7],
        mass: 126.9,
        label: "Йод",
        number: 53,
        name: "I",
        neutronCount: 74,
    },
    {
        electrons: [2, 8, 18, 18, 8],
        mass: 131.29,
        label: "Ксенон",
        number: 54,
        name: "Xe",
        neutronCount: 78,
    },
    {
        electrons: [2, 8, 18, 18, 8, 1],
        mass: 132.91,
        label: "Цезий",
        number: 55,
        name: "Cs",
        neutronCount: 78,
    },
    {
        electrons: [2, 8, 18, 18, 8, 2],
        mass: 137.33,
        label: "Барий",
        number: 56,
        name: "Ba",
        neutronCount: 82,
    },
    {
        electrons: [2, 8, 18, 18, 9, 2],
        mass: 138.91,
        label: "Лантан",
        number: 57,
        name: "La",
        neutronCount: 82,
    },
    {
        electrons: [2, 8, 18, 19, 9, 2],
        mass: 140.12,
        label: "Церий",
        number: 58,
        name: "Ce",
        neutronCount: 83,
    },
    {
        electrons: [2, 8, 18, 21, 8, 2],
        mass: 140.91,
        label: "Празеодим",
        number: 59,
        name: "Pr",
        neutronCount: 82,
    },
    {
        electrons: [2, 8, 18, 22, 8, 2],
        mass: 144.24,
        label: "Неодим",
        number: 60,
        name: "Nd",
        neutronCount: 85,
    },
    {
        electrons: [2, 8, 18, 23, 8, 2],
        mass: 144.91,
        label: "Прометий",
        number: 61,
        name: "Pm",
        neutronCount: 84,
    },
    {
        electrons: [2, 8, 18, 24, 8, 2],
        mass: 150.36,
        label: "Самарий",
        number: 62,
        name: "Sm",
        neutronCount: 89,
    },
    {
        electrons: [2, 8, 18, 25, 8, 2],
        mass: 151.96,
        label: "Европий",
        number: 63,
        name: "Eu",
        neutronCount: 89,
    },
    {
        electrons: [2, 8, 18, 25, 9, 2],
        mass: 157.25,
        label: "Гадолиний",
        number: 64,
        name: "Gd",
        neutronCount: 94,
    },
    {
        electrons: [2, 8, 18, 27, 8, 2],
        mass: 158.93,
        label: "Тербий",
        number: 65,
        name: "Tb",
        neutronCount: 94,
    },
    {
        electrons: [2, 8, 18, 28, 8, 2],
        mass: 162.5,
        label: "Диспрозий",
        number: 66,
        name: "Dy",
        neutronCount: 97,
    },
    {
        electrons: [2, 8, 18, 29, 8, 2],
        mass: 164.93,
        label: "Гольмий",
        number: 67,
        name: "Ho",
        neutronCount: 98,
    },
    {
        electrons: [2, 8, 18, 30, 8, 2],
        mass: 167.26,
        label: "Эрбий",
        number: 68,
        name: "Er",
        neutronCount: 100,
    },
    {
        electrons: [2, 8, 18, 31, 8, 2],
        mass: 168.93,
        label: "Тулий",
        number: 69,
        name: "Tm",
        neutronCount: 100,
    },
    {
        electrons: [2, 8, 18, 32, 8, 2],
        mass: 173.04,
        label: "Иттербий",
        number: 70,
        name: "Yb",
        neutronCount: 104,
    },
    {
        electrons: [2, 8, 18, 32, 9, 2],
        mass: 174.97,
        label: "Лютеций",
        number: 71,
        name: "Lu",
        neutronCount: 104,
    },
    {
        electrons: [2, 8, 18, 32, 10, 2],
        mass: 178.49,
        label: "Гафний",
        number: 72,
        name: "Hf",
        neutronCount: 107,
    },
    {
        electrons: [2, 8, 18, 32, 11, 2],
        mass: 180.95,
        label: "Тантал",
        number: 73,
        name: "Ta",
        neutronCount: 108,
    },
    {
        electrons: [2, 8, 18, 32, 12, 2],
        mass: 185.85,
        label: "Вольфрам",
        number: 74,
        name: "W",
        neutronCount: 112,
    },
    {
        electrons: [2, 8, 18, 32, 13, 2],
        mass: 186.21,
        label: "Рений",
        number: 75,
        name: "Re",
        neutronCount: 112,
    },
    {
        electrons: [2, 8, 18, 32, 14, 2],
        mass: 190.2,
        label: "Осмий",
        number: 76,
        name: "Os",
        neutronCount: 115,
    },
    {
        electrons: [2, 8, 18, 32, 15, 2],
        mass: 192.22,
        label: "Иридий",
        number: 77,
        name: "Ir",
        neutronCount: 116,
    },
    {
        electrons: [2, 8, 18, 32, 17, 1],
        mass: 195.08,
        label: "Платина",
        number: 78,
        name: "Pt",
        neutronCount: 118,
    },
    {
        electrons: [2, 8, 18, 32, 18, 1],
        mass: 196.97,
        label: "Золото",
        number: 79,
        name: "Au",
        neutronCount: 118,
    },
    {
        electrons: [2, 8, 18, 32, 18, 2],
        mass: 200.59,
        label: "Ртуть",
        number: 80,
        name: "Hg",
        neutronCount: 121,
    },
    {
        electrons: [2, 8, 18, 32, 18, 3],
        mass: 204.38,
        label: "Таллий",
        number: 81,
        name: "Tl",
        neutronCount: 124,
    },
    {
        electrons: [2, 8, 18, 32, 18, 4],
        mass: 207.19,
        label: "Свинец",
        number: 82,
        name: "Pb",
        neutronCount: 126,
    },
    {
        electrons: [2, 8, 18, 32, 18, 5],
        mass: 208.98,
        label: "Висмут",
        number: 83,
        name: "Bi",
        neutronCount: 126,
    },
    {
        electrons: [2, 8, 18, 32, 18, 6],
        mass: 209.98,
        label: "Полоний",
        number: 84,
        name: "Po",
        neutronCount: 126,
    },
    {
        electrons: [2, 8, 18, 32, 18, 7],
        mass: 209.99,
        label: "Астат",
        number: 85,
        name: "At",
        neutronCount: 125,
    },
    {
        electrons: [2, 8, 18, 32, 18, 8],
        mass: 222,
        label: "Радон",
        number: 86,
        name: "Rn",
        neutronCount: 136,
    },
    {
        electrons: [2, 8, 18, 32, 18, 8, 1],
        mass: 223,
        label: "Франций",
        number: 87,
        name: "Fr",
        neutronCount: 137,
    },
    {
        electrons: [2, 8, 18, 32, 18, 8, 2],
        mass: 226,
        label: "Радий",
        number: 88,
        name: "Ra",
        neutronCount: 139,
    },
    {
        electrons: [2, 8, 18, 32, 18, 9, 2],
        mass: 228,
        label: "Актиний",
        number: 89,
        name: "Ac",
        neutronCount: 140,
    },
    {
        electrons: [2, 8, 18, 32, 18, 10, 2],
        mass: 232.04,
        label: "Торий",
        number: 90,
        name: "Th",
        neutronCount: 143,
    },
    {
        electrons: [2, 8, 18, 32, 20, 9, 2],
        mass: 231.04,
        label: "Протактиний",
        number: 91,
        name: "Pa",
        neutronCount: 141,
    },
    {
        electrons: [2, 8, 18, 32, 21, 9, 2],
        mass: 238.03,
        label: "Уран",
        number: 92,
        name: "U",
        neutronCount: 147,
    },
    {
        electrons: [2, 8, 18, 32, 22, 9, 2],
        mass: 237.05,
        label: "Нептуний",
        number: 93,
        name: "Np",
        neutronCount: 145,
    },
    {
        electrons: [2, 8, 18, 32, 24, 8, 2],
        mass: 244.06,
        label: "Плутоний",
        number: 94,
        name: "Pu",
        neutronCount: 151,
    },
    {
        electrons: [2, 8, 18, 32, 25, 8, 2],
        mass: 243.06,
        label: "Америций",
        number: 95,
        name: "Am",
        neutronCount: 149,
    },
    {
        electrons: [2, 8, 18, 32, 25, 9, 2],
        mass: 247.07,
        label: "Кюрий",
        number: 96,
        name: "Cm",
        neutronCount: 152,
    },
    {
        electrons: [2, 8, 18, 32, 26, 9, 2],
        mass: 247.07,
        label: "Берклий",
        number: 97,
        name: "Bk",
        neutronCount: 151,
    },
    {
        electrons: [2, 8, 18, 32, 28, 8, 2],
        mass: 251.08,
        label: "Калифорний",
        number: 98,
        name: "Cf",
        neutronCount: 154,
    },
    {
        electrons: [2, 8, 18, 32, 29, 8, 2],
        mass: 252.08,
        label: "Энштейний",
        number: 99,
        name: "Es",
        neutronCount: 154,
    },
    {
        electrons: [2, 8, 18, 32, 30, 8, 2],
        mass: 257.1,
        label: "Фермий",
        number: 100,
        name: "Fm",
        neutronCount: 158,
    },
    {
        electrons: [2, 8, 18, 32, 31, 8, 2],
        mass: 258.1,
        label: "Менделевий",
        number: 101,
        name: "Md",
        neutronCount: 158,
    },
    {
        electrons: [2, 8, 18, 32, 32, 8, 2],
        mass: 259.1,
        label: "Нобелий",
        number: 102,
        name: "No",
        neutronCount: 158,
    },
    {
        electrons: [2, 8, 18, 32, 32, 9, 2],
        mass: 260.1,
        label: "Лоуренсий",
        number: 103,
        name: "Lr",
        neutronCount: 158,
    },
    {
        electrons: [2, 8, 18, 32, 32, 10, 2],
        mass: 261,
        label: "Резенфордий",
        number: 104,
        name: "Rf",
        neutronCount: 157,
    },
    {
        electrons: [2, 8, 18, 32, 32, 11, 2],
        mass: 262,
        label: "Дубний",
        number: 105,
        name: "Db",
        neutronCount: 157,
    },
    {
        electrons: [2, 8, 18, 32, 32, 12, 2],
        mass: 263,
        label: "Сиборгий",
        number: 106,
        name: "Sg",
        neutronCount: 157,
    },
    {
        electrons: [2, 8, 18, 32, 32, 13, 2],
        mass: 262,
        label: "Борий",
        number: 107,
        name: "Bh",
        neutronCount: 155,
    },
    {
        electrons: [2, 8, 18, 32, 32, 14, 2],
        mass: 265,
        label: "Хассий",
        number: 108,
        name: "Hs",
        neutronCount: 157,
    },
    {
        electrons: [2, 8, 18, 32, 32, 15, 2],
        mass: 266,
        label: "Мейтнерий",
        number: 109,
        name: "Mt",
        neutronCount: 157,
    },
    {
        electrons: [2, 8, 18, 32, 32, 17, 1],
        mass: 281,
        label: "Дармштадтий",
        number: 110,
        name: "Ds",
        neutronCount: 171,
    },
]